### ISSUE TITLE
Timing attack vulnerability on login

### ISSUE THREAD

**Issue by msyavuz** [jaequery/ult#13]
There seems to be a timing attack vulnerability here. Password comparison should happen regardless of user existing to mitigate the attack vector. Recently learned about this and its the first thing i checked.

[Code](https://github.com/jaequery/ult/blob/b9b3249e2adf41946f085a4e1f89874aea44d8c1/apps/server/src/user/user.service.ts#L57C5-L64C7)

[Reference](https://github.com/msyavuz/nest-auth-starter/blob/b41d7b829169fd5cf88d77796e50370ebd7e6e4c/src/auth/auth.service.ts#L60C1-L74C6)

**Comment by jaequery** [comment]
@msyavuz thank you, that's a very good point. would you be able to create a PR for it?
